In [89]:
import os
from pathlib import Path

import geopandas as gpd

In [124]:
data_path = Path(os.environ["DATA_PATH"])
generated_path = data_path / "generated"

In [144]:
df_features = gpd.read_file(generated_path / "features" / "filtered_places.gpkg")
df_polygons = gpd.read_file(
    generated_path
    / "polygons"
    / "joined_with_gadm"
    / "200_300"
    / "2020.gpkg",
)

In [145]:
test = (
    df_polygons
    .sjoin(df_features, how="inner", predicate="contains")
    .assign(tup=lambda df: df.apply(lambda row: (row["index_right"], row["place"]), axis=1))
)

In [147]:
test

,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,NAME_4,geometry,index_right,place,name,tup
0,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,None,"POLYGON ((-10333000 3961000, -10333000 3959000...",68934,town,Los Algodones,"(68934, town)"
1,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,None,"POLYGON ((-10353000 3954000, -10353000 3953000...",83088,village,Ejido Mérida,"(83088, village)"
2,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,None,"POLYGON ((-10341000 3954000, -10341000 3952000...",74834,village,García Sánchez,"(74834, village)"
3,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,None,"POLYGON ((-10343000 3953000, -10343000 3951000...",68936,village,Ejido República Mexicana,"(68936, village)"
4,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,None,"POLYGON ((-10348000 3952000, -10348000 3951000...",74764,town,Ciudad Morelos (Cuervos),"(74764, town)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24099,CHL,CHL.11_1,CHL.11.3_1,CHL.11.3.1_1,None,Chile,Magallanes y Antártica Chilena,Tierra del Fuego,Porvenir,None,"POLYGON ((-5114000 -6213000, -5114000 -6214000...",104875,town,Porvenir,"(104875, town)"
24100,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,None,"POLYGON ((-4890000 -6259000, -4890000 -6260000...",100607,city,Río Grande,"(100607, city)"
24101,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,None,"POLYGON ((-4795000 -6335000, -4795000 -6336000...",169392,village,Tolhuin,"(169392, village)"
24102,ARG,ARG.23_1,ARG.23.2_1,None,None,Argentina,Tierra del Fuego,Ushuaia,None,None,"POLYGON ((-4849000 -6364000, -4849000 -6366000...",101227,town,Ushuaia,"(101227, town)"
24103,CHL,CHL.11_1,CHL.11.1_1,CHL.11.1.1_1,None,Chile,Magallanes y Antártica Chilena,Antártica Chilena,Cabo de Hornos,None,"POLYGON ((-4790000 -6379000, -4790000 -6381000...",104880,town,Puerto Williams,"(104880, town)"

In [121]:
cities_processed

,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,NAME_4,geometry
0,MEX,MEX.3_1,MEX.3.2_2,NaN,NaN,México,Baja California,Mexicali,NaN,NaN,"POLYGON ((-10333000 3961000, -10333000 3959000..."
1,MEX,MEX.3_1,MEX.3.2_2,NaN,NaN,México,Baja California,Mexicali,NaN,NaN,"POLYGON ((-10353000 3954000, -10353000 3953000..."
2,MEX,MEX.3_1,MEX.3.2_2,NaN,NaN,México,Baja California,Mexicali,NaN,NaN,"POLYGON ((-10341000 3954000, -10341000 3952000..."
3,MEX,MEX.3_1,MEX.3.2_2,NaN,NaN,México,Baja California,Mexicali,NaN,NaN,"POLYGON ((-10343000 3953000, -10343000 3951000..."
4,MEX,MEX.3_1,MEX.3.2_2,NaN,NaN,México,Baja California,Mexicali,NaN,NaN,"POLYGON ((-10348000 3952000, -10348000 3951000..."
...,...,...,...,...,...,...,...,...,...,...,...
24115,CHL,CHL.11_1,CHL.11.3_1,CHL.11.3.1_1,NaN,Chile,Magallanes y Antártica Chilena,Tierra del Fuego,Porvenir,NaN,"POLYGON ((-5114000 -6213000, -5114000 -6214000..."
24116,ARG,ARG.23_1,ARG.23.1_1,NaN,NaN,Argentina,Tierra del Fuego,Rió Grande,NaN,NaN,"POLYGON ((-4890000 -6259000, -4890000 -6260000..."
24117,ARG,ARG.23_1,ARG.23.1_1,NaN,NaN,Argentina,Tierra del Fuego,Rió Grande,NaN,NaN,"POLYGON ((-4795000 -6335000, -4795000 -6336000..."
24118,ARG,ARG.23_1,ARG.23.2_1,NaN,NaN,Argentina,Tierra del Fuego,Ushuaia,NaN,NaN,"POLYGON ((-4849000 -6364000, -4849000 -6366000..."
24119,CHL,CHL.11_1,CHL.11.1_1,CHL.11.1.1_1,NaN,Chile,Magallanes y Antártica Chilena,Antártica Chilena,Cabo de Hornos,NaN,"POLYGON ((-4790000 -6379000, -4790000 -6381000..."

In [119]:
cities_in_two_countries_processed

,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,NAME_4,geometry
7918,DOM+HTI,DOM.17_1+HTI.5_1,DOM.17.4_1+HTI.5.1_1,HTI.5.1.3_1,HTI.5.1.3.1_1,Haití+República Dominicana,Monte Cristi (DOM)+Nord-Est (HTI),Fort-Liberté (HTI)+Pepillo Salcedo (DOM),Terrier (HTI),Bas Maribahoux (HTI),"POLYGON ((-6928000 2419000, -6928000 2418000, ..."
8353,DOM+HTI,DOM.4_1+HTI.5_1,DOM.4.1_1+HTI.5.3_1,HTI.5.3.1_1+HTI.5.3.3_1,HTI.5.3.1.1_1+HTI.5.3.3.3_1+HTI.5.3.3.4_1+HTI....,Haití+República Dominicana,Dajabón (DOM)+Nord-Est (HTI),Dajabón (DOM)+Ouanaminthe (HTI),Capotille (HTI)+Ouanaminthe (HTI),Capotille (HTI)+Haut Maribahoux (HTI)+Savane L...,"POLYGON ((-6936000 2403000, -6936000 2401000, ..."
8498,DOM+HTI,DOM.4_1+HTI.5_1,DOM.4.3_1+HTI.5.3_1,HTI.5.3.1_1+HTI.5.3.3_1,HTI.5.3.1.1_1+HTI.5.3.1.2_1+HTI.5.3.3.2_1+HTI....,Haití+República Dominicana,Dajabón (DOM)+Nord-Est (HTI),Loma de Cabrera (DOM)+Ouanaminthe (HTI),Capotille (HTI)+Ouanaminthe (HTI),Capotille (HTI)+Gens de Nantes (HTI)+Lamine (H...,"POLYGON ((-6930000 2389000, -6930000 2385000, ..."
8829,DOM+HTI,DOM.4_1+HTI.1_1,DOM.4.5_1+HTI.1.1_1,HTI.1.1.1_1,HTI.1.1.1.3_1,Haití+República Dominicana,Centre (HTI)+Dajabón (DOM),Cerca La Source (HTI)+Restauración (DOM),Cerca La Source (HTI),La Mielle (HTI),"POLYGON ((-6934000 2363000, -6934000 2362000, ..."
8836,DOM+HTI,DOM.12_1+DOM.4_1+HTI.1_1,DOM.12.6_1+DOM.4.5_1+HTI.1.1_1,HTI.1.1.1_1,HTI.1.1.1.3_1,Haití+República Dominicana,Centre (HTI)+Dajabón (DOM)+La Estrelleta (DOM),Cerca La Source (HTI)+Pedro Santana (DOM)+Rest...,Cerca La Source (HTI),La Mielle (HTI),"POLYGON ((-6932000 2361000, -6932000 2360000, ..."
...,...,...,...,...,...,...,...,...,...,...,...
22144,ARG+URY,ARG.8_1+URY.15_2,ARG.8.2_1+URY.15.1_2+URY.15.5_2,NaN,NaN,Argentina+Uruguay,Entre Ríos (ARG)+Salto (URY),Concordia (ARG)+NA (URY)+San Antonio (URY),NaN,NaN,"POLYGON ((-5274000 -3797000, -5274000 -3798000..."
22155,ARG+URY,ARG.8_1+URY.15_2,ARG.8.2_1+URY.15.1_2,NaN,NaN,Argentina+Uruguay,Entre Ríos (ARG)+Salto (URY),Concordia (ARG)+NA (URY),NaN,NaN,"POLYGON ((-5276000 -3811000, -5276000 -3812000..."
22184,ARG+URY,ARG.8_1+URY.11_2,ARG.8.2_1+URY.11.2_2,NaN,NaN,Argentina+Uruguay,Entre Ríos (ARG)+Paysandú (URY),Chapicuy (URY)+Concordia (ARG),NaN,NaN,"POLYGON ((-5267000 -3822000, -5267000 -3824000..."
22364,ARG+URY,ARG.8_1+URY.11_2,ARG.8.1_1+URY.11.4_2,NaN,NaN,Argentina+Uruguay,Entre Ríos (ARG)+Paysandú (URY),Colón (ARG)+Lorenzo Geyres (URY),NaN,NaN,"POLYGON ((-5256000 -3901000, -5256000 -3902000..."
22390,ARG+URY,ARG.8_1+URY.11_2,ARG.8.1_1+URY.11.1_2+URY.11.6_2,NaN,NaN,Argentina+Uruguay,Entre Ríos (ARG)+Paysandú (URY),Colón (ARG)+NA (URY)+Porvenir (URY),NaN,NaN,"POLYGON ((-5247000 -3907000, -5247000 -3909000..."