In [160]:
import os
from pathlib import Path

import geopandas as gpd

In [2]:
data_path = Path(os.environ["DATA_PATH"])
generated_path = data_path / "generated"
ghsl_path = Path(os.environ["GHSL_PATH"])

In [ ]:
df_cells = gpd.read_file(
    generated_path / "cells" / "pop_and_smod" / "200_300" / "2020.gpkg",
)
df_polygons = gpd.read_file(
    generated_path / "polygons" / "population" / "200_300" / "2020.gpkg",
)

In [177]:
out

,polygon_id,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,...,pop_rural_1980,pop_rural_1985,pop_rural_1990,pop_rural_1995,pop_rural_2000,pop_rural_2005,pop_rural_2010,pop_rural_2015,pop_rural_2020,geometry
0,p001034,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,2268.701927,2959.618227,3818.610212,4272.535401,4760.167696,5138.168347,252.459817,267.322066,264.238966,"POLYGON ((-10333000 3961000, -10333000 3959000..."
1,p001069,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,75.784695,103.751365,138.662225,202.744347,271.678609,311.444997,356.880156,392.892748,381.176590,"POLYGON ((-10353000 3954000, -10353000 3953000..."
2,p001072,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,102.866550,126.711897,154.868935,244.950582,324.053777,377.305868,430.419691,477.087452,469.662115,"POLYGON ((-10341000 3954000, -10341000 3952000..."
3,p001076,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,132.927448,162.047947,196.244056,251.213241,298.925936,388.678367,471.323241,546.413731,577.053235,"POLYGON ((-10343000 3953000, -10343000 3951000..."
4,p001086,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,3727.802767,4861.442301,496.137815,592.706876,697.806999,194.900279,206.674733,218.326721,217.636232,"POLYGON ((-10348000 3952000, -10348000 3951000..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23974,p044546,CHL,CHL.11_1,CHL.11.3_1,CHL.11.3.1_1,None,Chile,Magallanes y Antártica Chilena,Tierra del Fuego,Porvenir,...,4580.170029,4412.893645,4416.559395,4526.623202,4471.610882,4509.674547,4555.400660,4593.473461,4719.453422,"POLYGON ((-5114000 -6213000, -5114000 -6214000..."
23975,p044547,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,...,2435.712191,3497.606627,1130.629782,1122.928220,1348.187885,924.006368,1141.982246,1363.762253,1531.263447,"POLYGON ((-4890000 -6259000, -4890000 -6260000..."
23976,p044548,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,...,336.332463,539.676810,871.975260,1098.418435,1313.520567,1733.208112,2201.718269,2707.933114,3016.760547,"POLYGON ((-4795000 -6335000, -4795000 -6336000..."
23977,p044549,ARG,ARG.23_1,ARG.23.2_1,None,None,Argentina,Tierra del Fuego,Ushuaia,None,...,514.009313,517.512704,269.845142,351.197869,448.659707,593.275831,322.907942,100.095585,115.932586,"POLYGON ((-4849000 -6364000, -4849000 -6366000..."
23978,p044550,CHL,CHL.11_1,CHL.11.1_1,CHL.11.1.1_1,None,Chile,Magallanes y Antártica Chilena,Antártica Chilena,Cabo de Hornos,...,625.031125,623.980481,652.176075,730.940333,794.415635,887.254978,998.480747,1122.197068,1261.957610,"POLYGON ((-4790000 -6379000, -4790000 -6381000..."

In [173]:
1

1

In [168]:
df_polygons

,polygon_id,GID_0,GID_1,GID_2,GID_3,GID_4,NAME_0,NAME_1,NAME_2,NAME_3,...,pop_rural_1985,pop_rural_1990,pop_rural_1995,pop_rural_2000,pop_rural_2005,pop_rural_2010,pop_rural_2015,pop_rural_2020,geometry,countries
0,p001034,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,2959.618227,3818.610212,4272.535401,4760.167696,5138.168347,252.459817,267.322066,264.238966,"POLYGON ((-10333000 3961000, -10333000 3959000...",[MEX]
1,p001069,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,103.751365,138.662225,202.744347,271.678609,311.444997,356.880156,392.892748,381.176590,"POLYGON ((-10353000 3954000, -10353000 3953000...",[MEX]
2,p001072,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,126.711897,154.868935,244.950582,324.053777,377.305868,430.419691,477.087452,469.662115,"POLYGON ((-10341000 3954000, -10341000 3952000...",[MEX]
3,p001076,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,162.047947,196.244056,251.213241,298.925936,388.678367,471.323241,546.413731,577.053235,"POLYGON ((-10343000 3953000, -10343000 3951000...",[MEX]
4,p001086,MEX,MEX.3_1,MEX.3.2_2,None,None,México,Baja California,Mexicali,None,...,4861.442301,496.137815,592.706876,697.806999,194.900279,206.674733,218.326721,217.636232,"POLYGON ((-10348000 3952000, -10348000 3951000...",[MEX]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,p044546,CHL,CHL.11_1,CHL.11.3_1,CHL.11.3.1_1,None,Chile,Magallanes y Antártica Chilena,Tierra del Fuego,Porvenir,...,4412.893645,4416.559395,4526.623202,4471.610882,4509.674547,4555.400660,4593.473461,4719.453422,"POLYGON ((-5114000 -6213000, -5114000 -6214000...",[CHL]
24078,p044547,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,...,3497.606627,1130.629782,1122.928220,1348.187885,924.006368,1141.982246,1363.762253,1531.263447,"POLYGON ((-4890000 -6259000, -4890000 -6260000...",[ARG]
24079,p044548,ARG,ARG.23_1,ARG.23.1_1,None,None,Argentina,Tierra del Fuego,Rió Grande,None,...,539.676810,871.975260,1098.418435,1313.520567,1733.208112,2201.718269,2707.933114,3016.760547,"POLYGON ((-4795000 -6335000, -4795000 -6336000...",[ARG]
24080,p044549,ARG,ARG.23_1,ARG.23.2_1,None,None,Argentina,Tierra del Fuego,Ushuaia,None,...,517.512704,269.845142,351.197869,448.659707,593.275831,322.907942,100.095585,115.932586,"POLYGON ((-4849000 -6364000, -4849000 -6366000...",[ARG]
24081,p044550,CHL,CHL.11_1,CHL.11.1_1,CHL.11.1.1_1,None,Chile,Magallanes y Antártica Chilena,Antártica Chilena,Cabo de Hornos,...,623.980481,652.176075,730.940333,794.415635,887.254978,998.480747,1122.197068,1261.957610,"POLYGON ((-4790000 -6379000, -4790000 -6381000...",[CHL]

In [31]:
df_cells

                                                  geometry    cell_id country
4        POLYGON ((-10689000 3377000, -10689000 3378000...  c00020260     MEX
5        POLYGON ((-10689000 3378000, -10689000 3379000...  c00020261     MEX
10       POLYGON ((-10688000 3375000, -10688000 3376000...  c00030681     MEX
11       POLYGON ((-10688000 3376000, -10688000 3377000...  c00030682     MEX
12       POLYGON ((-10688000 3377000, -10688000 3378000...  c00030683     MEX
...                                                    ...        ...     ...
7008805  POLYGON ((-4629000 -6379000, -4629000 -6378000...  c63173884     ARG
7008806  POLYGON ((-4629000 -6378000, -4629000 -6377000...  c63173885     ARG
7008814  POLYGON ((-4629000 -6370000, -4629000 -6369000...  c63173893     ARG
7008815  POLYGON ((-4629000 -6369000, -4629000 -6368000...  c63173894     ARG
7008816  POLYGON ((-4629000 -6368000, -4629000 -6367000...  c63173895     ARG

[6931136 rows x 3 columns]

In [27]:
df_cells

                                                  geometry    cell_id
0        POLYGON ((-10690000 3378000, -10690000 3379000...  c00009838
1        POLYGON ((-10689000 3374000, -10689000 3375000...  c00020257
2        POLYGON ((-10689000 3375000, -10689000 3376000...  c00020258
3        POLYGON ((-10689000 3376000, -10689000 3377000...  c00020259
4        POLYGON ((-10689000 3377000, -10689000 3378000...  c00020260
...                                                    ...        ...
7008825  POLYGON ((-4628000 -6372000, -4628000 -6371000...  c63184314
7008826  POLYGON ((-4628000 -6371000, -4628000 -6370000...  c63184315
7008827  POLYGON ((-4628000 -6370000, -4628000 -6369000...  c63184316
7008828  POLYGON ((-4628000 -6369000, -4628000 -6368000...  c63184317
7008829  POLYGON ((-4628000 -6368000, -4628000 -6367000...  c63184318

[7008830 rows x 2 columns]

In [28]:
len(cells_map)

6931136